[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eo_man"
version = "0.1.35"
description = "Tool to managed EnOcean Devices and to generate Home Assistant Configuration."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
    { name = "Philipp Grimm" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "requests>=2.20.0"
]

[tool.setuptools]
include-package-data = true  # Enables package data inclusion

[tool.setuptools.package-dir]
"my_package" = "eo_man"

[tool.setuptools.package-data]
"my_package" = [
    "../docs/**",
    "../changes.md",
    "../demo.eodm",
    "../eo_man.bat",
]

[project.urls]
"Homepage" = "https://github.com/grimmpp/enocean-device-manager"